name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Chekout repository
        uses: actions/checkout@v5

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild .\PhysicsGame.sln /p:Configuration=Release 


      - name: Create artifact directory
        run: mkdir artifact
        
      - name: Copy the executable to the artifact directory
        run: copy ./Build/PhysicsGame/Release/win32/PhysicsGame.exe ./artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          path: ./artifact
          name: Physics-artifact



  
